// npm run export -- THE WORLD AS A GLB FOR BLENDER (r60).
//
// *"Is there any way to get this scene into a Blender file? I'd love to get a visual read, do some curating of where
// buildings go and build more onto it."* The world is generated by code at load, so there is no file to hand over --
// until this: it boots the REAL module headless (the same page `npm run sim` builds), lets `init()` build every
// district, and writes what is in the scene out as glTF binary, which Blender imports with File > Import > glTF.
//
//   exports/rollergirl_world.glb       the picture: one object per district chunk, baked into world space, grouped
//                                      under hub / slice / orbital / shores / city / backdrop, with vertex colours,
//                                      the generated textures (paving, sandstone, plaster ... and their normal maps)
//                                      embedded as PNG, and every grind rail as an EDGE polyline under `rails`
//   exports/rollergirl_collision.glb   what she actually collides with, in the handoff's own naming: `deck_` floors
//                                      (one mesh per district) and every solid as a `bld_` box -- the same convention
//                                      `levelIngest` reads back, so a curated copy can come home through it
//
// WHAT IS NOT IN IT, AND WHY: her (draco wants a Worker headless), his weirdport kit and BKG0-3 (already his Blender
// files -- the plain stand-in boxes are exported where the kit would sit), the canvas-painted sign atlas (no 2D
// canvas headless, so signs come out as bare quads), particles, glow cards and the sky. The detail shader is a
// runtime effect and does not survive into a file either.
//
// Units are metres, +Y up (Blender's importer converts to Z up). Run it again after any change to the world.

import fs from 'fs'; import os from 'os'; import path from 'path';
import { pathToFileURL } from 'url';

if (!fs.existsSync('node_modules/three/package.json')) {
  fs.mkdirSync('node_modules/three', { recursive: true });
  fs.writeFileSync('node_modules/three/package.json', JSON.stringify({
    name: 'three', version: '0.180.0-vendored', type: 'module', main: 'index.js', exports: { '.': './index.js' } }));
  fs.writeFileSync('node_modules/three/index.js', "export * from '../../vendor/three.module.min.js';\n");
}
const TMP = path.join(os.tmpdir(), 'rollergirl-sim');
fs.mkdirSync(TMP, { recursive: true });
const ROOT = pathToFileURL(process.cwd() + '/').href;
fs.writeFileSync(path.join(TMP, 'three-shim.mjs'), `
export * from '${ROOT}vendor/three.module.min.js';
import * as T from '${ROOT}vendor/three.module.min.js';
class FakeTarget { constructor(w,h,o){ this.width=w; this.height=h; this.texture=new T.Texture(); } setSize(){} dispose(){} }
export { FakeTarget as WebGLRenderTarget };
class FakeRenderer { constructor(){ this.domElement = globalThis.document.createElement('canvas');
  this.shadowMap={enabled:false,type:0}; this.info={autoReset:true,render:{calls:0,triangles:0},reset(){}};
  this.capabilities={isWebGL2:true,getMaxAnisotropy:()=>1,precision:'highp'};
  this.outputColorSpace=''; this.toneMapping=0; this.toneMappingExposure=1; }
  setSize(){} setPixelRatio(){} setClearColor(){} setRenderTarget(){} clear(){} render(){} dispose(){}
  compile(){} getContext(){ return {getParameter:()=>0}; } getDrawingBufferSize(v){ return v.set(1280,720); } initTexture(){} }
export { FakeRenderer as WebGLRenderer };
class FakePMREM { constructor(){} fromEquirectangular(){ return { texture: new T.Texture() }; } compileEquirectangularShader(){} dispose(){} }
export { FakePMREM as PMREMGenerator };
`);
const boot = fs.readFileSync('tools/boot.mjs', 'utf8');
const stubs = boot.slice(boot.indexOf('// STUBS:START'), boot.indexOf('// STUBS:END'));
(0, eval)(stubs);
// r64: the export is of the world this file builds, not of his zones. r66: `npm run export kit` is the ramp kit instead.
// r88: `npm run export:park` -- the schematic park ALONE (`parks/<name>.json`, built from his drawing), as a reference
// for a Blender session rebuilding parks from images: see the PARKMODE block below.
const PARKMODE = process.argv[2] === 'park';
const KITMODE = process.argv[2] === 'kit' || PARKMODE;
// r83: `npm run export:lib` -- the gallery ALONE (every kind at every size, no example parks), into `handoff/`, as the
// piece library a Blender session duplicates from. The full kit with both parks is 18 MB; the library is the part to hand over.
const LIBMODE = KITMODE && process.argv[3] === 'lib';
// r132: `npm run export:spillway` -- THE SPILLWAY (world 5) whole, the same two files under its own name
const SPWMODE = process.argv[2] === 'spillway';
globalThis.localStorage.setItem('rg.world', KITMODE ? '2' : SPWMODE ? '5' : '0');
if (KITMODE) globalThis.__kitKeep = 1;
if (PARKMODE && process.argv[3]) globalThis.localStorage.setItem('rg.park', process.argv[3]);      // r88: `npm run export:park -- <name>`     // each piece keeps a copy of its own triangles to be written out

const html = fs.readFileSync('index.html', 'utf8');
let src = html.match(/<script type="module">([\s\S]*?)<\/script>/)[1];
src = src.replace(/(from\s*)['"]three['"]/g, `$1'${pathToFileURL(path.join(TMP, 'three-shim.mjs')).href}'`)
         .replace(/(from\s*)['"]\.\/vendor\//g, `$1'${ROOT}vendor/`);
const f = path.join(TMP, 'sim.mjs'); fs.writeFileSync(f, src);
const quiet = console.warn; console.warn = () => {};
await import(pathToFileURL(f).href + '?t=' + Date.now());
for (let i = 0; i < 400 && !globalThis.rg.ready(); i++) await new Promise(r => setTimeout(r, 10));
console.warn = quiet;
const rg = globalThis.rg;
const THREE = await import(pathToFileURL(path.join(TMP, 'three-shim.mjs')).href);
if (!rg.ready()) { console.error('the module never became ready'); process.exit(1); }

// ---- driving ----
import sharp from 'sharp';
const OUT = 'exports';
fs.mkdirSync(OUT, { recursive: true });
const t0 = Date.now();

// ---------------------------------------------------------------- a minimal glTF 2.0 binary writer
function glbWriter() {
  const J = { asset: { version: '2.0', generator: 'rollergirl tools/export.mjs' }, scene: 0, scenes: [{ nodes: [] }], nodes: [], meshes: [],
    accessors: [], bufferViews: [], buffers: [{ byteLength: 0 }], materials: [], textures: [], images: [], samplers: [{ wrapS: 10497, wrapT: 10497 }] };
  const chunks = []; let off = 0;
  const view = (buf, target) => { const pad = (4 - (off % 4)) % 4; if (pad) { chunks.push(Buffer.alloc(pad)); off += pad; }
    const b = Buffer.from(buf.buffer, buf.byteOffset, buf.byteLength); chunks.push(b);
    J.bufferViews.push(Object.assign({ buffer: 0, byteOffset: off, byteLength: b.length }, target ? { target } : {})); off += b.length; return J.bufferViews.length - 1; };
  const acc = (arr, type, comp, minmax) => { const n = { VEC3: 3, VEC2: 2, VEC4: 4, SCALAR: 1 }[type];
    const a = { bufferView: view(arr, comp === 5125 ? 34963 : 34962), componentType: comp, count: arr.length / n, type };
    if (minmax) { const mn = [Infinity, Infinity, Infinity], mx = [-Infinity, -Infinity, -Infinity];
      for (let i = 0; i < arr.length; i += 3) for (let k = 0; k < 3; k++) { mn[k] = Math.min(mn[k], arr[i + k]); mx[k] = Math.max(mx[k], arr[i + k]); } a.min = mn; a.max = mx; }
    J.accessors.push(a); return J.accessors.length - 1; };
  const img = png => { const v = view(new Uint8Array(png.buffer, png.byteOffset, png.length)); J.images.push({ bufferView: v, mimeType: 'image/png' });
    J.textures.push({ source: J.images.length - 1, sampler: 0 }); return J.textures.length - 1; };
  return { J, acc, img,
    node(name, parent, extra) { J.nodes.push(Object.assign({ name }, extra || {})); const i = J.nodes.length - 1;
      if (parent == null) J.scenes[0].nodes.push(i); else (J.nodes[parent].children || (J.nodes[parent].children = [])).push(i); return i; },
    write(file) { const bin = Buffer.concat(chunks), bpad = (4 - (bin.length % 4)) % 4, B = Buffer.concat([bin, Buffer.alloc(bpad)]);
      J.buffers[0].byteLength = B.length;
      let js = Buffer.from(JSON.stringify(J)); const jpad = (4 - (js.length % 4)) % 4; js = Buffer.concat([js, Buffer.alloc(jpad, 0x20)]);
      const head = Buffer.alloc(12); head.writeUInt32LE(0x46546c67, 0); head.writeUInt32LE(2, 4); head.writeUInt32LE(12 + 8 + js.length + 8 + B.length, 8);
      const jh = Buffer.alloc(8); jh.writeUInt32LE(js.length, 0); jh.writeUInt32LE(0x4e4f534a, 4);
      const bh = Buffer.alloc(8); bh.writeUInt32LE(B.length, 0); bh.writeUInt32LE(0x004e4942, 4);
      fs.writeFileSync(file, Buffer.concat([head, jh, js, bh, B])); return 12 + 16 + js.length + B.length; } };
}

// one kit piece as an `fn_` node (shared by `export:kit`, `export:lib` and r88's `export:park`)
// `G` (r91): the frame of the group node it is written under ({x, y, z, yaw}) -- the piece's transform is then RELATIVE to
// it (a glTF Y turn by a takes local +Z to (sin a, cos a), the game's yaw sense, so the inverse is the same turn by -a)
function writePiece(W, pc, parent, cnt, spec, K, G) {
    const T = pc.T, fx = Math.sin(T.yaw), fz = Math.cos(T.yaw);
    const toLocal = (X, Y, Z) => { const dx = X - T.x, dz = Z - T.z; return [dx * fz - dz * fx, Y - T.y, dx * fx + dz * fz]; };
    const n = cnt[pc.kind + pc.size] = (cnt[pc.kind + pc.size] || 0) + 1, name = `fn_${pc.kind}_${pc.size}_${n}`;
    const S = rg.KSZ[pc.size] || {}, o = { ...pc.o }; delete o.yaw;
    const paths = pc.rails || (pc.rail ? [pc.rail] : []);
    // TOP LEVEL = what rebuilds it (kind, size, the options it was built with); `info` = reference numbers only, and it
    // is an object so `levelFn` never reads it back as an option (a roll-in reads `o.r` and `o.deck` -- the size's
    // radius handed back as one would build a different piece)
    const extras = { fn: pc.kind, size: pc.size, ...o, label: pc.label || '', info: { H: S.H, r: S.r && +S.r.toFixed(3), lip: S.lip && +S.lip.toFixed(3),
      sweep_deg: S.sweep && Math.round(S.sweep * 180 / Math.PI), deck: K.deck, footprint_w_by_u: [+(pc.wid || 0).toFixed(2), +(pc.len || 0).toFixed(2)], top: pc.h != null ? +(+pc.h).toFixed(2) : undefined,
      // r67: WHERE THE NEXT PIECE'S ORIGIN GOES, in this node's own frame (glTF: +Z along, +X across) and the turn about Y
      out: pc.out ? { at: [+pc.out.w.toFixed(3), +pc.out.y.toFixed(3), +pc.out.u.toFixed(3)], yaw_deg: +(pc.out.dyaw * 180 / Math.PI).toFixed(2) } : undefined,
      out2: pc.out2 ? { at: [+pc.out2.w.toFixed(3), +pc.out2.y.toFixed(3), +pc.out2.u.toFixed(3)], yaw_deg: +(pc.out2.dyaw * 180 / Math.PI).toFixed(2) } : undefined,
      rails: paths.length || undefined } };
    let tr = [T.x, T.y, T.z], yaw = T.yaw;
    if (G) { const dx = T.x - G.x, dz = T.z - G.z, c = Math.cos(G.yaw), sn = Math.sin(G.yaw); tr = [dx * c - dz * sn, T.y - G.y, dx * sn + dz * c].map(v => +v.toFixed(5)); yaw = T.yaw - G.yaw; }
    const node = { translation: tr, rotation: [0, Math.sin(yaw / 2), 0, Math.cos(yaw / 2)], extras };
    // r67: A RAIL IS DRAWN BY `railDraw`, NOT INTO THE PIECE'S TRIANGLES -- so a rail-only piece would arrive in Blender
    // as an empty. Each path gets a six-sided tube along its points (its TOP is the line she rides), steel or booster pink.
    const wpos = (pc.pos || []).slice(), wcol = (pc.col || []).slice();
    if (!pc.rail) for (const R of paths) {
      const pts = [R.segs[0].a, ...R.segs.map(q => q.b)], r = 0.045, c = R.boost ? [1, 0.17, 0.38] : [0.6, 0.62, 0.68], ring = [];
      pts.forEach((q, i) => { const a = pts[Math.max(0, i - 1)], b = pts[Math.min(pts.length - 1, i + 1)];
        const t = new THREE.Vector3(b.x - a.x, b.y - a.y, b.z - a.z).normalize(), up0 = Math.abs(t.y) > 0.9 ? new THREE.Vector3(1, 0, 0) : new THREE.Vector3(0, 1, 0);
        const sd = new THREE.Vector3().crossVectors(t, up0).normalize(), up = new THREE.Vector3().crossVectors(sd, t).normalize();
        ring.push([...Array(6)].map((_, k) => { const a6 = k / 6 * Math.PI * 2; return [q.x + (sd.x * Math.cos(a6) + up.x * Math.sin(a6)) * r - up.x * r,
          q.y + (sd.y * Math.cos(a6) + up.y * Math.sin(a6)) * r - up.y * r, q.z + (sd.z * Math.cos(a6) + up.z * Math.sin(a6)) * r - up.z * r]; })); });
      for (let i = 0; i < ring.length - 1; i++) for (let k = 0; k < 6; k++) { const A = ring[i][k], B = ring[i][(k + 1) % 6], C = ring[i + 1][(k + 1) % 6], D = ring[i + 1][k];
        for (const v of [A, C, B, A, D, C]) { wpos.push(...v); wcol.push(...c); } }
    }
    if (wpos.length) {
      const pos = new Float32Array(wpos.length), col = new Float32Array(wcol);
      for (let i = 0; i < wpos.length; i += 3) pos.set(toLocal(wpos[i], wpos[i + 1], wpos[i + 2]), i);
      const nrm = new Float32Array(pos.length);
      for (let t = 0; t < pos.length; t += 9) { const ax = pos[t], ay = pos[t + 1], az = pos[t + 2], ux = pos[t + 3] - ax, uy = pos[t + 4] - ay, uz = pos[t + 5] - az, vx = pos[t + 6] - ax, vy = pos[t + 7] - ay, vz = pos[t + 8] - az;
        let nx = uy * vz - uz * vy, ny = uz * vx - ux * vz, nz = ux * vy - uy * vx; const l = Math.hypot(nx, ny, nz) || 1; nx /= l; ny /= l; nz /= l;
        for (let k = 0; k < 3; k++) nrm.set([nx, ny, nz], t + k * 3); }
      W.J.meshes.push({ name, primitives: [prim({ pos, nrm, col, uv: null }, 0, W)] }); node.mesh = W.J.meshes.length - 1;
    }
    const ni = W.node(name, parent, node);
    paths.forEach((R, j) => { const pts = [R.segs[0].a, ...R.segs.map(q => q.b)], pos = new Float32Array(pts.length * 3), gn = 'guide_' + name + (paths.length > 1 ? '_' + j : '');
      pts.forEach((q, i) => pos.set(toLocal(q.x, q.y, q.z), i * 3));
      W.J.meshes.push({ name: gn, primitives: [{ attributes: { POSITION: W.acc(pos, 'VEC3', 5126, true) }, mode: 3 }] });
      W.node(gn, ni, { mesh: W.J.meshes.length - 1, extras: { part_of: name, info: { boost: R.boost, closed: !!R.closed } } }); });
    spec.push({ name, park: pc.park || undefined, area: pc.area || undefined, combo: pc.combo || undefined, ...extras, at: [+T.x.toFixed(2), +T.y.toFixed(2), +T.z.toFixed(2)], yaw_deg: Math.round(T.yaw * 180 / Math.PI),
      local: G ? { at: tr.map(v => +v.toFixed(3)), yaw_deg: +(yaw * 180 / Math.PI).toFixed(2) } : undefined });
  return name;
}

// ---------------------------------------------------------------- r66: THE RAMP KIT
// One object per piece, named `fn_<kind>_<size>_<n>`, its mesh in its OWN frame (origin on the ground at the middle of
// the front edge, local +Z the way the rider goes up it, +X across) and the node placed where the gallery has it --
// so in Blender each one is a placeholder he can duplicate, move and turn, and a GLB of them coming back is rebuilt by
// `levelIngest` into the real pieces. The extras carry the kind, the size and every option the piece was built with.

// ---------------------------------------------------------------- r88: THE REFERENCE PARK
// *"If you export out the current skate park, that might act as a guide."* The park he rides and likes is the schematic
// park: `parks/mega_skatepark.json`, every piece placed in the PIXELS of his drawing, built by `kitSheet` out of the kit.
// This writes it alone, re-centred on its own middle, as the same `fn_` nodes `export:kit` writes -- so a Blender session
// can open it, read it, duplicate from it, and a copy that comes back is rebuilt by `levelIngest` into the same pieces --
// PLUS the three things a piece list alone would lose, each of which changes how it rides:
//   deck_park_ground   the park's floor, CUT by every sunk bowl and pool. Dropped on a plain flat floor, a sunk bowl is a
//                      bowl under a lid; this is the floor with the holes in it, and it is collided.
//   art_ground_<n>     the grass and paint he drew -- a picture only, a hair over the floor, never collided
//   marker_spawn_park / marker_spot_<area>   where she drops in, and the ➤ stop of every area
// and beside it: `<name>_layout.json` (every piece with its area, kind, size, place, turn and options, and the LAYOUT numbers --
// what faces what, how far apart, how much run-up), `<name>_plan.png` (a top-down height map of the collider itself,
// labelled), and the drawing and the schematic it was built from.
// `npm run sim parkref` re-imports the GLB turned round and moved, and checks it rebuilds the same floors, solids and rails.
if (PARKMODE) {
  const K = rg.KITW, S = rg.SHEET, J = S.data, W = glbWriter(), spec = [], cnt = {};
  if (!J) { console.error('the schematic never loaded: ' + S.err); process.exit(1); }
  const name = J.name ? String(J.name).toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') : 'park';
  const key = (S.url.match(/([^/]+)\.json$/) || [0, name])[1];
  const DIR = 'handoff/park_reference'; fs.mkdirSync(DIR, { recursive: true });
  W.J.materials.push({ name: 'kit', pbrMetallicRoughness: { baseColorFactor: [1, 1, 1, 1], metallicFactor: 0, roughnessFactor: 0.85 } });
  const pieces = K.pieces.filter(pc => pc.park && /^sheet /.test(pc.park));
  const cx = +((S.x0 + S.x1) / 2).toFixed(2), cz = +((S.z0 + S.z1) / 2).toFixed(2);
  const root = W.node('park_' + key, null, { translation: [-cx, 0, -cz], extras: { source: S.url, world_centre: [cx, 0, cz],
    note: 'children are in the game world frame; this node moves the park so its middle is at the origin' } });
  const areaNode = {}, areaName = id => (S.areas.find(a => a.id === id) || { name: 'misc' }).name;
  const nodeFor = id => areaNode[id] != null ? areaNode[id] : (areaNode[id] = W.node(`area_${id}_${areaName(id).replace(/[^a-z0-9]+/gi, '_')}`, root, { extras: { area: id, name: areaName(id) } }));
  for (const pc of pieces) writePiece(W, pc, nodeFor(pc.area || 'x'), cnt, spec, K);
  // THE FLOOR, cut -- the same triangulation `kitSheet` does, from the same polygon and the same holes
  const tri = (P, Hs) => { const V = P.concat(...Hs), out = [];
    for (const [a, b, c] of THREE.ShapeUtils.triangulateShape(P.map(([x, z]) => new THREE.Vector2(x, z)), Hs.map(H => H.map(([x, z]) => new THREE.Vector2(x, z))))) out.push(V[a], V[b], V[c]);
    return out; };
  const flatMesh = (nm, tris, y, rgb, parent) => {
    const pos = [], col = [], nrm = [];
    for (let i = 0; i < tris.length; i += 3) { let [A, B, C] = [tris[i], tris[i + 1], tris[i + 2]];
      const up = (B[1] - A[1]) * (C[0] - A[0]) - (B[0] - A[0]) * (C[1] - A[1]); if (up <= 0) [B, C] = [C, B];      // wound to face UP
      for (const q of [A, B, C]) { pos.push(q[0], y, q[1]); col.push(...rgb); nrm.push(0, 1, 0); } }
    W.J.meshes.push({ name: nm, primitives: [prim({ pos: new Float32Array(pos), nrm: new Float32Array(nrm), col: new Float32Array(col), uv: null }, 0, W)] });
    return W.node(nm, parent, { mesh: W.J.meshes.length - 1 }); };
  const rgbOf = c => { const n = typeof c === 'number' ? c : 0xdddddd; return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255].map(v => Math.pow(v, 2.2)); };
  const C_ = c => typeof c === 'number' ? c : (J.tints && J.tints[c] != null) ? C_(J.tints[c]) : typeof c === 'string' ? parseInt(c.replace('#', ''), 16) : 0xdddddd;
  const W2 = S.W;
  (J.ground || []).forEach((G, gi) => { const P = G.pts.map(W2);
    if (gi === 0) flatMesh('deck_park_ground', tri(P, S.holes), 0.004, rgbOf(C_(G.color)), root);
    else flatMesh('art_ground_' + gi, tri(P, []), 0.004 + (G.lift || 0) + 0.002 * gi, rgbOf(C_(G.color)), root); });
  // where she drops in, and every area's stop (`heading` is degrees in the game's sense, as `levelIngest` reads it)
  const mk = (nm, q, extra) => W.node(nm, root, { translation: [q[0], q[1], q[2]], extras: { heading: +(q[3] * 180 / Math.PI).toFixed(1), ...extra } });
  if (S.spawn) mk('marker_spawn_park', S.spawn, { kind: 'spawn' });
  for (const A of S.areas) { const q = rg.CITY.spots['sheet ' + A.name]; if (q) mk('marker_spot_' + A.id + '_' + A.name.replace(/[^a-z0-9]+/gi, '_'), q, { spot: A.name }); }
  const sz = W.write(`${DIR}/${key}.glb`);

  // ---- THE HEIGHT GRID OFF THE COLLIDER (the plan below and the "lines" measurement both read it), at `mpp`
  const mpp = 0.15, pad = 8, X0 = S.x0 - pad, Z0 = S.z0 - pad, w = Math.ceil((S.x1 - S.x0 + 2 * pad) / mpp), h = Math.ceil((S.z1 - S.z0 + 2 * pad) / mpp);
  const H = new Float32Array(w * h);
  for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) { const q = rg.groundAt(X0 + (i + 0.5) * mpp, Z0 + (j + 0.5) * mpp, 60, 0); H[j * w + i] = q.hit ? q.floor : NaN; }
  // ---- THE LAYOUT, MEASURED ON WHAT SHE RIDES, not on what the pieces are called (most of this park is traced `wall`s,
  // which have no single facing): from every ramp face, roll DOWN it, across whatever floor is at its foot, and measure
  // how far she goes before the ground rises again -- the run-out from one feature into the next. Any park, from any
  // tool, can be measured the same way, which is the point: a rebuild of this park should come out with the same numbers.
  const Hg = (i, j) => (i < 1 || j < 1 || i >= w - 1 || j >= h - 1) ? NaN : H[j * w + i];
  const runs = [], tall = [];
  for (let j = 2; j < h - 2; j += 3) for (let i = 2; i < w - 2; i += 3) {
    const y = Hg(i, j); if (Number.isNaN(y)) continue;
    const gx = (Hg(i + 1, j) - Hg(i - 1, j)) / (2 * mpp), gz = (Hg(i, j + 1) - Hg(i, j - 1)) / (2 * mpp), g = Math.hypot(gx, gz);
    if (!(g > 0.18 && g < 12)) continue;                        // a riding face: 10 to 85 degrees
    const dx = -gx / g, dz = -gz / g;                          // downhill
    let k = 1, toe = -1, prev = y, out = null;
    for (; k < 60 / mpp; k++) { const yy = Hg(Math.round(i + dx * k), Math.round(j + dz * k)); if (Number.isNaN(yy)) break;
      const step = (yy - prev) / mpp; prev = yy;
      if (toe < 0) { if (step > -0.05) toe = k; continue; }      // still on the way down the face
      if (step > 0.18) { out = (k - toe) * mpp; break; } }       // the ground rises again: the next feature
    if (toe >= 0) runs.push(out); }
  const rv = runs.filter(v => v != null).sort((p, q) => p - q);
  const pct = (L, f) => L.length ? +L[Math.min(L.length - 1, Math.floor(L.length * f))].toFixed(1) : null;
  const byKind = {}; for (const pc of pieces) { const k = pc.kind + ' ' + pc.size; byKind[k] = (byKind[k] || 0) + 1; }
  const furn = /^(fence|planter|lamp|shade|bleachers)$/;
  // the gap from each riding piece to its nearest neighbour (box to box), which is the push room between features
  const ride = pieces.filter(pc => pc.bb && !furn.test(pc.kind)), gaps = [];
  for (const a of ride) { let best = 1e9; for (const b of ride) { if (a === b || (a.group && a.group === b.group)) continue;
    const gx = Math.max(0, Math.max(a.bb[0], b.bb[0]) - Math.min(a.bb[3], b.bb[3])), gz = Math.max(0, Math.max(a.bb[2], b.bb[2]) - Math.min(a.bb[5], b.bb[5]));
    best = Math.min(best, Math.hypot(gx, gz)); } if (best < 1e8) gaps.push(best); }
  gaps.sort((p, q) => p - q);
  const areas = S.areas.map(A => { const L = A.recs.filter(r => r.bb); if (!L.length) return { id: A.id, name: A.name, pieces: 0, kinds: [] };
    const x0 = Math.min(...L.map(r => r.bb[0])), x1 = Math.max(...L.map(r => r.bb[3])), z0 = Math.min(...L.map(r => r.bb[2])), z1 = Math.max(...L.map(r => r.bb[5]));
    const top = Math.max(...L.map(r => r.bb[4]));
    return { id: A.id, name: A.name, pieces: A.recs.length, size_m: [+(x1 - x0).toFixed(0), +(z1 - z0).toFixed(0)], tallest_m: +top.toFixed(1),
      kinds: [...new Set(A.recs.map(r => r.kind + ' ' + r.size))] }; });
  const layout = { park_size_m: [+(S.x1 - S.x0).toFixed(0), +(S.z1 - S.z0).toFixed(0)], pieces: pieces.length, riding_pieces: ride.length,
    rails: pieces.reduce((n, pc) => n + (pc.rails ? pc.rails.length : pc.rail ? 1 : 0), 0), by_kind: byKind,
    // from the foot of a ramp, rolling down its fall line: how far to the next rise, and how often there is one inside 60 m
    ramp_to_ramp: { samples: runs.length, reaches_another_within_60m: runs.length ? +(rv.length / runs.length).toFixed(2) : null,
      run_out_m: { p10: pct(rv, 0.1), p25: pct(rv, 0.25), median: pct(rv, 0.5), p75: pct(rv, 0.75), p90: pct(rv, 0.9) } },
    nearest_neighbour_gap_m: { p10: pct(gaps, 0.1), median: pct(gaps, 0.5), p90: pct(gaps, 0.9) }, areas };
  fs.writeFileSync(`${DIR}/${key}_layout.json`, JSON.stringify({ source: S.url, drawing: J.image || null, name: J.name, mpp: J.mpp, pin: J.pin,
    origin_note: `pieces are in the game world frame; subtract world_centre to get the GLB's own frame (the park's middle at the origin)`,
    world_centre: [cx, 0, cz], sizes: Object.fromEntries(Object.entries(rg.KSZ).map(([k, v]) => [k, { H: v.H, r: +v.r.toFixed(3), lip: +v.lip.toFixed(3) }])),
    layout, pieces: spec }, null, 1));
  fs.copyFileSync('docs/RAMP_KIT.md', `${DIR}/RAMP_KIT.md`);      // the schematic format and every piece's options, so the folder stands alone
  for (const f of fs.readdirSync('parks')) if (f.startsWith(key)) fs.copyFileSync('parks/' + f, `${DIR}/${f.replace(/\.json$/, '_schematic.json')}`);

  // ---- THE PLAN: a top-down height map read off the COLLIDER (so it is what she rides, not what is drawn)
  const img = Buffer.alloc(w * h * 3), top = Math.max(...pieces.map(pc => pc.bb ? pc.bb[4] : 0), 1);
  const lerp = (a, b, t) => a.map((v, k) => v + (b[k] - v) * t);
  for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) { const k = j * w + i, y = H[k];
    let c;
    if (Number.isNaN(y)) c = [40, 40, 52];
    else { const yl = H[k - 1] ?? y, yu = H[k - w] ?? y, sx = Number.isNaN(yl) ? 0 : y - yl, sz = Number.isNaN(yu) ? 0 : y - yu;
      const shade = Math.max(0.55, Math.min(1.15, 1 + (-sx * 0.7 - sz * 0.7) / mpp * 0.35)), steep = Math.min(1, Math.hypot(sx, sz) / mpp);
      if (y < -0.05) c = lerp([150, 200, 235], [40, 90, 170], Math.min(1, -y / 4));
      else if (y < 0.05) c = [226, 222, 232];
      else c = lerp([255, 214, 170], [200, 60, 60], Math.min(1, y / top));
      c = lerp(c, [90, 70, 110], steep * 0.35).map(v => Math.max(0, Math.min(255, v * shade))); }
    img[k * 3] = c[0]; img[k * 3 + 1] = c[1]; img[k * 3 + 2] = c[2]; }
  const px = (x, z) => [((x - X0) / mpp).toFixed(1), ((z - Z0) / mpp).toFixed(1)];
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" font-family="sans-serif">`;
  for (const P of rg.PATHS) { if (!P.segs || !P.segs.length) continue; const pts = [P.segs[0].a, ...P.segs.map(q => q.b)];
    if (!pts.every(q => q.x >= X0 && q.x <= X0 + w * mpp && q.z >= Z0 && q.z <= Z0 + h * mpp)) continue;
    svg += `<polyline fill="none" stroke="${P.boost ? '#ff2b6a' : '#20202a'}" stroke-width="3" points="${pts.map(q => px(q.x, q.z).join(',')).join(' ')}"/>`; }
  for (const A of areas) { const L = (S.areas.find(a => a.id === A.id) || { recs: [] }).recs.filter(r => r.bb); if (!L.length || A.size_m[0] > 120) continue;      // not the park-wide ones (fence, lamps, trees)
    const mx = L.reduce((s, r) => s + (r.bb[0] + r.bb[3]) / 2, 0) / L.length, mz = L.reduce((s, r) => s + (r.bb[2] + r.bb[5]) / 2, 0) / L.length, [u, v] = px(mx, mz);
    svg += `<text x="${u}" y="${v}" font-size="24" font-weight="bold" text-anchor="middle" fill="#111" stroke="#fff" stroke-width="5" paint-order="stroke">${A.id} ${A.name.replace(/[<&>]/g, '')}</text>`; }
  if (S.spawn) { const [u, v] = px(S.spawn[0], S.spawn[2]); svg += `<circle cx="${u}" cy="${v}" r="10" fill="#18c06a" stroke="#000" stroke-width="3"/><text x="${+u + 14}" y="${+v + 8}" font-size="22" fill="#000" stroke="#fff" stroke-width="4" paint-order="stroke">SPAWN</text>`; }
  const bar = 20 / mpp; svg += `<rect x="20" y="${h - 46}" width="${bar}" height="10" fill="#000"/><text x="20" y="${h - 54}" font-size="20" fill="#000" stroke="#fff" stroke-width="4" paint-order="stroke">20 m   (+X right, +Z down: the drawing's way up, and Blender's top view)</text>`;
  svg += `<text x="20" y="34" font-size="22" fill="#000" stroke="#fff" stroke-width="4" paint-order="stroke">${J.name || key}: height read off the collider. grey = floor, peach to red = up to ${top.toFixed(1)} m, blue = sunk. Lines are rails (pink = booster)</text></svg>`;
  await sharp(img, { raw: { width: w, height: h, channels: 3 } }).composite([{ input: Buffer.from(svg), top: 0, left: 0 }]).png().toFile(`${DIR}/${key}_plan.png`);
  console.log(`park: ${pieces.length} pieces in ${areas.length} areas -> ${DIR}/${key}.glb (${(sz / 1e6).toFixed(2)} MB), _layout.json, _schematic.json, _plan.png (${w}x${h})`);
  const RR = layout.ramp_to_ramp; console.log(`  ramp to ramp: ${RR.samples} face samples, ${Math.round(RR.reaches_another_within_60m * 100)}% meet another rise inside 60 m, run-out p25/median/p75 ${RR.run_out_m.p25}/${RR.run_out_m.median}/${RR.run_out_m.p75} m; nearest-neighbour gap p10/median/p90 ${layout.nearest_neighbour_gap_m.p10}/${layout.nearest_neighbour_gap_m.median}/${layout.nearest_neighbour_gap_m.p90} m`);
  process.exit(0);
}

if (KITMODE) {
  const K = rg.KITW, W = glbWriter(), spec = [];
  W.J.materials.push({ name: 'kit', pbrMetallicRoughness: { baseColorFactor: [1, 1, 1, 1], metallicFactor: 0, roughnessFactor: 0.85 } });
  const root = W.node('ramp_kit', null), cnt = {}, park = W.node('example_park', null), zones = {};
  const zoneOf = z => zones[z] != null ? zones[z] : (zones[z] = W.node('park_' + z.replace(/[^a-z0-9]+/gi, '_'), park));
  for (const pc of K.pieces) {
    if ((LIBMODE && pc.park) || pc.combo) continue;
    writePiece(W, pc, pc.park ? zoneOf(pc.park) : root, cnt, spec, K);
  }
  // r91: THE COMBOS, each under its own group node at its own frame (origin on the ground at the middle of its entry
  // edge, +Z into it, +X across -- a piece's convention, one level up), its pieces `fn_` nodes RELATIVE to it. Move or
  // turn the group in Blender and every piece goes with it; `levelIngest` reads the pieces through `matrixWorld`.
  const C = rg.COMBOS, combos = [], cnode = C.list.length ? W.node('combos', null) : null;
  // what `npm run sim combos` measured riding each one, if it has been run (it writes this file, then calls this export)
  const TF = 'handoff/rollergirl_combo_tests.json', TESTS = fs.existsSync(TF) ? JSON.parse(fs.readFileSync(TF, 'utf8')).tests || {} : {};
  // a combo-local [u, w, heading, what] in the glTF frame: [x = w, y, z = u], heading in degrees about +Y from +Z
  const io = (q, y) => ({ at: [+(+q[1]).toFixed(2), +(y || 0).toFixed(2), +(+q[0]).toFixed(2)], heading_deg: +((q[2] || 0) * 180 / Math.PI).toFixed(1), what: q[3] });
  for (const c of C.list) {
    const T = c.T, yq = [0, Math.sin(T.yaw / 2), 0, Math.cos(T.yaw / 2)];
    const at = q => { const P = rg.kT(T, q[0], q[1], 0), g = rg.groundAt(P.x, P.z, 30, 0); return g.hit ? g.floor - T.y : 0; };
    const meta = { combo: c.key, name: c.name, what: c.what, from_photos: c.src,
      footprint: { u: [c.fp[0], c.fp[1]], w: [c.fp[2], c.fp[3]], size_m: [+(c.fp[3] - c.fp[2]).toFixed(1), +(c.fp[1] - c.fp[0]).toFixed(1)], note: 'u = along +Z (into it), w = along +X' },
      entries: c.in.map(q => io(q, at(q))), exits: c.out.map(q => io(q, at(q))), heights: c.heights, rails: c.rails, tested: TESTS[c.key] || undefined };
    const g = W.node('combo_' + c.key, cnode, { translation: [T.x, T.y, T.z], rotation: yq, extras: meta });
    const names = c.recs.map(pc => writePiece(W, pc, g, cnt, spec, K, T));
    combos.push({ ...meta, node: 'combo_' + c.key, world_at: [T.x, T.y, T.z], world_yaw_deg: Math.round(T.yaw * 180 / Math.PI), pieces: names });
  }
  const base = LIBMODE ? 'handoff/rollergirl_kit_library' : `${OUT}/rollergirl_kit`;
  if (LIBMODE) fs.mkdirSync('handoff', { recursive: true });
  const sz = W.write(`${base}.glb`);
  fs.writeFileSync(`${base}.json`, JSON.stringify({ sizes: Object.fromEntries(Object.entries(rg.KSZ).map(([k, v]) => [k, { H: v.H, r: +v.r.toFixed(3), lip: +v.lip.toFixed(3), sweep_deg: Math.round(v.sweep * 180 / Math.PI) }])),
    width: K.W, deck: K.deck, coping: K.cope, rail_step: 1.2,
    combo_frame: 'origin on the ground at the middle of the entry edge, +Z into the combo, +X across, +Y up; entries/exits are [x, y, z] in that frame, heading in degrees about +Y from +Z',
    combos, pieces: spec }, null, 1));
  console.log(`kit: ${spec.length} pieces (${combos.length} combos) -> ${base}.glb (${(sz / 1e6).toFixed(2)} MB) + ${base}.json`);
  process.exit(0);
}

// which district a thing belongs to, by where it is -- the gates are at the plaza's edges, |x| or |z| ~ 100
const district = SPWMODE ? ((x, z) => Math.hypot(x, z) > 380 ? 'backdrop' : z > 136 && Math.abs(x) > 100 ? 'reservoir' : z >= 0 || (Math.abs(x) > 70 && z > (Math.abs(x) - 70) * 0.404) ? 'dam' : z > -84 ? 'plaza' : 'harbour') : (x, z) => Math.hypot(x, z) > 380 ? 'backdrop' : Math.abs(x) < 100 && Math.abs(z) < 100 ? 'hub' : Math.abs(x) >= Math.abs(z) ? (x < 0 ? 'slice' : 'shores') : (z < 0 ? 'orbital' : rg.PARKD && rg.PARKD.on ? 'park' : 'city');     // r90: the north is the skate park district unless ?city=1

// ---------------------------------------------------------------- the picture
const W = glbWriter(), WW = W, groups = {}, grp = name => groups[name] != null ? groups[name] : (groups[name] = W.node(name, null));
const matIx = new Map(), texIx = new Map();
async function texOf(t) {
  if (!t || !t.image || !t.image.data || !t.image.width) return null;
  if (texIx.has(t)) return texIx.get(t);
  const { data, width, height } = t.image, ch = data.length / (width * height);
  if (ch !== 4 && ch !== 3) return null;
  const png = await sharp(Buffer.from(data.buffer, data.byteOffset, data.byteLength), { raw: { width, height, channels: ch } }).png().toBuffer();
  const i = W.img(png); texIx.set(t, i); return i;
}
async function matOf(m) {
  if (matIx.has(m)) return matIx.get(m);
  const o = { name: m.name || m.type, pbrMetallicRoughness: { baseColorFactor: [1, 1, 1, 1], metallicFactor: 0, roughnessFactor: 0.9 } }, pb = o.pbrMetallicRoughness;
  if (m.color) pb.baseColorFactor = [m.color.r, m.color.g, m.color.b, m.opacity != null ? m.opacity : 1];
  if (m.isShaderMaterial) { pb.baseColorFactor = [0.1, 0.7, 0.65, 1]; o.name = 'water'; }
  if (m.metalness != null) pb.metallicFactor = m.metalness; if (m.roughness != null) pb.roughnessFactor = m.roughness;
  if (m.emissive && (m.emissive.r + m.emissive.g + m.emissive.b) > 0) o.emissiveFactor = [m.emissive.r, m.emissive.g, m.emissive.b].map(v => Math.min(1, v * (m.emissiveIntensity || 1)));
  if (m.isMeshBasicMaterial && m.color) { o.emissiveFactor = [m.color.r, m.color.g, m.color.b]; o.extensions = { KHR_materials_unlit: {} }; }
  const bt = await texOf(m.map); if (bt != null) pb.baseColorTexture = { index: bt };
  const nt = await texOf(m.normalMap); if (nt != null) o.normalTexture = { index: nt };
  if (m.transparent || m.alphaTest > 0) { o.alphaMode = m.alphaTest > 0 ? 'MASK' : 'BLEND'; if (m.alphaTest > 0) o.alphaCutoff = m.alphaTest; }
  if (m.side === THREE.DoubleSide) o.doubleSided = true;
  W.J.materials.push(o); const i = W.J.materials.length - 1; matIx.set(m, i); return i;
}
// one primitive from a geometry range, baked through a matrix
function bake(g, M, start, count) {
  const P = g.attributes.position, N = g.attributes.normal, U = g.attributes.uv, C = g.attributes.color, I = g.index;
  const nv = I ? count : count, nm = new THREE.Matrix3().getNormalMatrix(M), v = new THREE.Vector3();
  const pos = new Float32Array(nv * 3), nrm = N ? new Float32Array(nv * 3) : null, uv = U ? new Float32Array(nv * 2) : null, col = C ? new Float32Array(nv * 3) : null;
  for (let k = 0; k < nv; k++) { const i = I ? I.getX(start + k) : start + k;
    v.fromBufferAttribute(P, i).applyMatrix4(M); pos.set([v.x, v.y, v.z], k * 3);
    if (N) { v.fromBufferAttribute(N, i).applyMatrix3(nm).normalize(); nrm.set([v.x, v.y, v.z], k * 3); }
    if (U) uv.set([U.getX(i), U.getY(i)], k * 2);
    if (C) col.set([C.getX(i), C.getY(i), C.getZ(i)], k * 3); }
  // a mirrored matrix reverses the winding
  if (M.determinant() < 0) for (let k = 0; k + 2 < nv; k += 3) for (const A of [pos, nrm, col].filter(Boolean)) for (let c = 0; c < 3; c++) { const a = (k + 1) * 3 + c, b = (k + 2) * 3 + c, t = A[a]; A[a] = A[b]; A[b] = t; }
  return { pos, nrm, uv, col };
}
const merge = parts => { const cat = k => { const L = parts.filter(p => p[k]); if (L.length !== parts.length) return null; const n = L.reduce((s, p) => s + p[k].length, 0), o = new Float32Array(n); let q = 0; for (const p of L) { o.set(p[k], q); q += p[k].length; } return o; };
  return { pos: cat('pos'), nrm: cat('nrm'), uv: cat('uv'), col: cat('col') }; };
// welded: a vertex shared by every triangle that uses it (same position, normal, uv and colour), so the file
// carries an index instead of three copies -- about half the size, and Blender sees connected faces
function weld(b) {
  const n = b.pos.length / 3, map = new Map(), idx = new Uint32Array(n), keep = [];
  const q = (v, s) => Math.round(v * s);
  for (let i = 0; i < n; i++) {
    let k = q(b.pos[i * 3], 1e4) + ',' + q(b.pos[i * 3 + 1], 1e4) + ',' + q(b.pos[i * 3 + 2], 1e4);
    if (b.nrm) k += '|' + q(b.nrm[i * 3], 1e3) + ',' + q(b.nrm[i * 3 + 1], 1e3) + ',' + q(b.nrm[i * 3 + 2], 1e3);
    if (b.uv) k += '|' + q(b.uv[i * 2], 1e4) + ',' + q(b.uv[i * 2 + 1], 1e4);
    if (b.col) k += '|' + q(b.col[i * 3], 1e3) + ',' + q(b.col[i * 3 + 1], 1e3) + ',' + q(b.col[i * 3 + 2], 1e3);
    let j = map.get(k); if (j === undefined) { j = keep.length; map.set(k, j); keep.push(i); } idx[i] = j;
  }
  const pick = (A, w) => { if (!A) return null; const o = new Float32Array(keep.length * w); keep.forEach((i, j) => { for (let c = 0; c < w; c++) o[j * w + c] = A[i * w + c]; }); return o; };
  return { pos: pick(b.pos, 3), nrm: pick(b.nrm, 3), uv: pick(b.uv, 2), col: pick(b.col, 3), idx };
}
function prim(b0, mat, W = WW) {
  const b = weld(b0), at = { POSITION: W.acc(b.pos, 'VEC3', 5126, true) };
  if (b.nrm) at.NORMAL = W.acc(b.nrm, 'VEC3', 5126); if (b.uv) at.TEXCOORD_0 = W.acc(b.uv, 'VEC2', 5126); if (b.col) at.COLOR_0 = W.acc(b.col, 'VEC3', 5126);
  return { attributes: at, indices: W.acc(b.idx, 'SCALAR', 5125), material: mat, mode: 4 };
}
const skip = o => (o.material && !Array.isArray(o.material) && o.material.side === THREE.BackSide) || o.isSkinnedMesh || o.isPoints || o.isSprite || o.isLine || !o.visible || o.renderOrder <= -50 || /sky|trail|spark|tail|gey|glow|planet|whale|craft|train/i.test(o.name || '');
let nMesh = 0, nTri = 0; const counts = {};
rg.scene.updateMatrixWorld(true);
const todo = [];
rg.scene.traverse(o => { if (!o.isMesh || skip(o)) return;
  let p = o.parent; while (p) { if (!p.visible || (p !== rg.scene && skip(p))) return; p = p.parent; }   // a planet group's spheres are unnamed
  if (o.isMesh && o.geometry && o.geometry.attributes.position) todo.push(o); });
for (const o of todo) {
  const g = o.geometry, mats = Array.isArray(o.material) ? o.material : [o.material];
  const groupsG = g.groups && g.groups.length ? g.groups : [{ start: 0, count: g.index ? g.index.count : g.attributes.position.count, materialIndex: 0 }];
  const insts = o.isInstancedMesh ? Array.from({ length: o.count }, (_, i) => { const m = new THREE.Matrix4(); o.getMatrixAt(i, m); return m.premultiply(o.matrixWorld); }) : [o.matrixWorld];
  g.computeBoundingSphere(); const c = g.boundingSphere ? g.boundingSphere.center.clone().applyMatrix4(insts[0]) : new THREE.Vector3();
  const prims = [];
  for (const G of groupsG) { const m = mats[G.materialIndex || 0]; if (!m) continue;
    const b = merge(insts.map(M => bake(g, M, G.start, Math.min(G.count, (g.index ? g.index.count : g.attributes.position.count) - G.start))));
    if (!b.pos || !b.pos.length) continue; prims.push(prim(b, await matOf(m))); nTri += b.pos.length / 9; }
  if (!prims.length) continue;
  W.J.meshes.push({ name: o.name || 'mesh', primitives: prims });
  // a ring of far towers has its centre near the middle of the world, so size decides that one
  const dk = g.boundingSphere && g.boundingSphere.radius > 250 ? 'backdrop' : district(c.x, c.z); counts[dk] = (counts[dk] || 0) + 1;
  W.node(o.name || 'mesh' + nMesh, grp(dk), { mesh: W.J.meshes.length - 1 }); nMesh++;
}
// the rails, as edges -- a polyline per path, named for it, so where every grind runs can be seen and moved
{ const R = W.node('rails', null); let nR = 0;
  for (const P of rg.PATHS) { if (!P.segs.length) continue;
    const pts = [P.segs[0].a, ...P.segs.map(s => s.b)], pos = new Float32Array(pts.length * 3); pts.forEach((q, i) => pos.set([q.x, q.y, q.z], i * 3));
    W.J.meshes.push({ name: 'rail_' + P.name, primitives: [{ attributes: { POSITION: W.acc(pos, 'VEC3', 5126, true) }, mode: 3 }] });
    const q = pts[0]; W.node(`rail_${P.name.replace(/\s+/g, '_')}_${nR++}`, R, { mesh: W.J.meshes.length - 1, extras: { boost: P.boost || 0, closed: !!P.closed, link: !!P.link, district: district(q.x, q.z) } }); } }
// MARKERS: the things the game reads by position, as named empties (or flat zone meshes) with extras, so a curated
// copy keeps them -- every ➤ spot and the spawn, the water zones, the launchers, the boost lanes, the trampolines,
// the hydrants and the gems. `extras.kind` says what each one is.
{ const M = W.node('markers', null), sub = {}, at = n => sub[n] != null ? sub[n] : (sub[n] = W.node('markers_' + n, M));
  const yq = h => [0, Math.sin(h / 2), 0, Math.cos(h / 2)];      // a heading about +Y: forward is (sin h, cos h)
  const empty = (grpN, name, x, y, z, extras, h) => W.node(name, at(grpN), Object.assign({ translation: [x, y, z], extras }, h != null ? { rotation: yq(h) } : {}));
  const S = rg.SPAWN; empty('spots', 'spawn', S.x, S.y, S.z, { kind: 'spawn' }, 0);
  for (const [k, v] of Object.entries(rg.CITY.spots)) empty('spots', 'spot_' + k.replace(/\s+/g, '_'), v[0], v[1], v[2], { kind: 'spot', spot: k, heading: v[3], district: district(v[0], v[2]) }, v[3]);
  const O = rg.ORB || {};
  (O.water || []).forEach((w, i) => { const pos = new Float32Array([w.x0, w.y, w.z0, w.x0, w.y, w.z1, w.x1, w.y, w.z1, w.x1, w.y, w.z0]);
    W.J.meshes.push({ name: 'zone_water_' + i, primitives: [{ attributes: { POSITION: W.acc(pos, 'VEC3', 5126, true) }, indices: W.acc(new Uint32Array([0, 1, 2, 0, 2, 3]), 'SCALAR', 5125), mode: 4 }] });
    W.node('zone_water_' + i, at('water'), { mesh: W.J.meshes.length - 1, extras: { kind: 'water', splash: !!w.splash, surface_y: w.y, district: district((w.x0 + w.x1) / 2, (w.z0 + w.z1) / 2) } }); });
  (O.launch || []).forEach((L, i) => empty('launchers', 'launcher_' + i, L.x, L.y, L.z, { kind: 'launcher', radius: L.r, target: [L.tx, L.ty, L.tz], apex: L.apex }));
  (O.bounce || []).forEach((B, i) => empty('trampolines', 'trampoline_' + i, B.x, B.y, B.z, { kind: 'trampoline', radius: B.r }));
  (O.lanes || []).forEach((L, i) => { const pos = new Float32Array(L.pts.length * 3); L.pts.forEach((q, j) => pos.set([q.x, q.y, q.z], j * 3));
    W.J.meshes.push({ name: 'lane_' + i, primitives: [{ attributes: { POSITION: W.acc(pos, 'VEC3', 5126, true) }, mode: 3 }] });
    W.node('lane_' + (L.name || 'lane').replace(/\s+/g, '_') + '_' + i, at('boost_lanes'), { mesh: W.J.meshes.length - 1, extras: { kind: 'boost_lane', half_width: L.hw, speed: L.v, accel: L.acc, governed: L.gov || 0 } }); });
  (rg.HYD.list || []).forEach((H, i) => empty('hydrants', 'hydrant_' + i, H.x, H.y || 0, H.z, { kind: 'hydrant' }));
  (rg.GEM.list || []).forEach((G, i) => empty('gems', 'gem_' + i, G.x, G.y, G.z, { kind: 'gem' }));
  console.log(`markers: ${Object.keys(rg.CITY.spots).length + 1} spots, ${(O.water || []).length} water, ${(O.launch || []).length} launchers, ${(O.lanes || []).length} lanes, ${(O.bounce || []).length} trampolines, ${(rg.HYD.list || []).length} hydrants, ${(rg.GEM.list || []).length} gems`); }
if (W.J.materials.some(m => m.extensions)) W.J.extensionsUsed = ['KHR_materials_unlit'];
const WNAME = SPWMODE ? 'rollergirl_spillway' : 'rollergirl_world';
const sz = W.write(`${OUT}/${WNAME}.glb`);
console.log(`world: ${nMesh} objects, ${Math.round(nTri / 1000)}k triangles, ${W.J.materials.length} materials, ${W.J.images.length} textures, ${rg.PATHS.length} rails -> ${OUT}/${WNAME}.glb (${(sz / 1e6).toFixed(1)} MB)`);
console.log('  by district: ' + Object.entries(counts).map(([k, v]) => `${k} ${v}`).join(', '));

// ---------------------------------------------------------------- the collider, in the handoff's naming
{ const C = glbWriter(), cg = {}, cgrp = n => cg[n] != null ? cg[n] : (cg[n] = C.node(n, null));
  C.J.materials.push({ name: 'floor', pbrMetallicRoughness: { baseColorFactor: [0.3, 0.8, 0.4, 1], metallicFactor: 0, roughnessFactor: 1 } },
                     { name: 'wall', pbrMetallicRoughness: { baseColorFactor: [0.9, 0.4, 0.3, 1], metallicFactor: 0, roughnessFactor: 1 } });
  // floors: every collider triangle, one mesh per district (the tops of solids are in here too)
  const V = rg.TRI.v, n = rg.TRI.n || (V ? V.length / 12 : 0), by = {};
  for (let t = 0; t < n; t++) { const o = t * 12, dk = district((V[o] + V[o + 3] + V[o + 6]) / 3, (V[o + 2] + V[o + 5] + V[o + 8]) / 3); (by[dk] || (by[dk] = [])).push(o); }
  for (const [dk, L] of Object.entries(by)) { const pos = new Float32Array(L.length * 9); L.forEach((o, i) => { for (let k = 0; k < 9; k++) pos[i * 9 + k] = V[o + k]; });
    C.J.meshes.push({ name: 'deck_' + dk, primitives: [{ attributes: { POSITION: C.acc(pos, 'VEC3', 5126, true) }, material: 0, mode: 4 }] });
    C.node('deck_' + dk, cgrp(dk), { mesh: C.J.meshes.length - 1 }); }
  // solids: every box, as a box, named bld_<district>_<tag>_<n>
  let nb = 0;
  for (const b of rg.SOLID.all) { if (!b.live) continue;
    const cs = (lx, lz) => [b.cx + lx * b.c + lz * b.s, b.cz - lx * b.s + lz * b.c], y0 = b.y0, y1 = b.y1;
    const q = [cs(-b.hx, -b.hz), cs(b.hx, -b.hz), cs(b.hx, b.hz), cs(-b.hx, b.hz)], P = [];
    const v = (i, y) => [q[i][0], y, q[i][1]], quad = (a, b2, c, d) => P.push(...a, ...b2, ...c, ...a, ...c, ...d);
    quad(v(0, y1), v(3, y1), v(2, y1), v(1, y1)); quad(v(0, y0), v(1, y0), v(2, y0), v(3, y0));
    for (let i = 0; i < 4; i++) { const j = (i + 1) % 4; quad(v(i, y0), v(i, y1), v(j, y1), v(j, y0)); }
    const pos = new Float32Array(P), dk = district(b.cx, b.cz), nm = `bld_${dk}_${(b.tag || 'box').replace(/[^a-z0-9]+/gi, '_')}_${nb++}`;
    C.J.meshes.push({ name: nm, primitives: [{ attributes: { POSITION: C.acc(pos, 'VEC3', 5126, true) }, material: 1, mode: 4 }] });
    C.node(nm, cgrp(dk), { mesh: C.J.meshes.length - 1, extras: { kind: 'solid', tag: b.tag || '', top_is_floor: !!b.floor, yaw: b.yaw } }); }
  const CNAME = SPWMODE ? 'rollergirl_spillway_collision' : 'rollergirl_collision';
  const s2 = C.write(`${OUT}/${CNAME}.glb`);
  console.log(`collision: ${n} floor triangles, ${nb} boxes -> ${OUT}/${CNAME}.glb (${(s2 / 1e6).toFixed(1)} MB)`); }
console.log(`done in ${((Date.now() - t0) / 1000).toFixed(1)} s`);
process.exit(0);
